# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 50, 4, 268700)),
        ),
        migrations.AlterField(
            model_name='plants',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 50, 4, 253105)),
        ),
        migrations.AlterField(
            model_name='rain',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 50, 4, 268700)),
        ),
        migrations.AlterField(
            model_name='soil',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 50, 4, 253105)),
        ),
        migrations.AlterField(
            model_name='temp',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 50, 4, 253105)),
        ),
        migrations.AlterField(
            model_name='water',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 17, 50, 4, 253105)),
        ),
    ]
